// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqwZZXAxiH44erIFsuKUXxYyW-j2VqFU8',
    appId: '1:568879113866:android:bd7ef2c56025190d3c2f73',
    messagingSenderId: '568879113866',
    projectId: 'goldencare-68364',
    databaseURL: 'https://goldencare-68364-default-rtdb.firebaseio.com',
    storageBucket: 'goldencare-68364.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Wd4iXq7a64Pl2b_XBU7sJOB_Vwiis9Y',
    appId: '1:568879113866:ios:4f17bf40b1c5e5c33c2f73',
    messagingSenderId: '568879113866',
    projectId: 'goldencare-68364',
    databaseURL: 'https://goldencare-68364-default-rtdb.firebaseio.com',
    storageBucket: 'goldencare-68364.firebasestorage.app',
    iosBundleId: 'com.goldencare2.goldenCare2',
  );
}
